use Object.assign instead of spread operators
monksoftware/monk-log pull request #3
Opened 2019-02-20 18:18 UTC by F4bio16

2019-02-21 13:29 UTC, LeartS requested changes

2019-02-21 13:29 UTC, LeartS commented on lib/log.js
> +        name, level || this.getLevel(), Object.assign(this.options, options))
Attento che `Object.assign` muta e sovrascrive il target object, in questo caso `this.options`!

Il che significa che se fai:
```js
const childLogger = parentLogger.getLogger('child', null, {template: 'logging inutile'})
```
Da quel momento in poi viene usato il template inutile sia dal figlio (giustamente) che dal padre (errore)! Non ho testato ma sono abbastanza sicuro sia così.

La versione safe da usare per evitare questo problema è `Object.assign({}, this.options, options)`

2019-02-21 13:29 UTC, LeartS commented on lib/log.js
> +  constructor (name, level, options = {}) {
Non dovrebbe essere necessario perchè non puoi inizializzare `MonkLogger` direttamente, non essendo esportato, ma solo da `<loggeresistente>.getLogger()`, e quello ha il default oggetto vuoto su options.

A meno che non sei stronzo e fai porcate tipo

```js
const log = require('monk-log')
new log.constructor('logger-degli-stronzi')
```

2019-02-21 13:54 UTC, F4bio16 commented on lib/log.js
> +  constructor (name, level, options = {}) {
L'avevo fatto perché ricevevo l'errore

```
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
```

problema che dopo le modifiche pare sia risolto

2019-02-21 14:00 UTC, F4bio16 commented on lib/log.js
> +  constructor (name, level, options = {}) {
Senza il default:

```javascript
   const monklog = require('./').getLogger('child-logger')
```

restituisce l'errore:

```
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at new MonkLogger (/home/fabio/node-projects/monk-log/lib/log.js:52:27)
```

2019-02-21 14:09 UTC, LeartS commented on lib/log.js
> +  constructor (name, level, options = {}) {
Sì hai ragione, perchè vedo che effettivamente il root logger esportato non passa options:

```js
const defaultLogger = new MonkLogger('root')
```

Ok per il default `= {}`

2019-02-21 14:09 UTC, LeartS commented on lib/log.js
> +    this.options = Object.assign(options, defaultLogLevelOptions)
Anche qua stai sovrascrivendo options con le opzioni di default

2019-02-22 12:10 UTC, LeartS approved these changes

2019-02-22 12:11 UTC, merged